# © Dmitry Detkov 2024
# Изделие №4 Detkov Pro. - openldap
# File: compose.override.yml

x-logging-opts: &logging-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '10M'
      max-file: 3

services:

  openldap:
    <<: *logging-opts
    image: openldap
    hostname: openldap
    environment:
      LDAP_FORCE_STARTTLS: "true"
      LDAP_DOMAIN: "eden.local"
      LDAP_BASEDN: "dc=eden,dc=local"
      LDAP_ORGANISATION: "Detkov Pro., Inc."
      LDAP_BINDDN: "cn=admin,dc=eden,dc=local"
    ports:
      - '10389:10389'
      - '10636:10636'
  volumes:
    - data_volume:/var/lib/ldap/

volumes:
   data_volume:
