#!/usr/bin/with-contenv bash
set -eux

configure_tls() {
    echo "Настроить TLS..."
    ldapmodify -Y EXTERNAL -H ldapi:/// -f ${CONFIG_DIR}/tls.ldif -Q
}


configure_logging() {
    echo "Настроить журнал..."
    ldapmodify -Y EXTERNAL -H ldapi:/// -f ${CONFIG_DIR}/logging.ldif -Q
}

configure_msad_features(){
  echo "Настройка расширений MS-AD"
  ldapmodify -Y EXTERNAL -H ldapi:/// -f ${CONFIG_DIR}/msad.ldif -Q
}

configure_admin_config_pw(){
  echo "Настроить пароль конфигурации администратора..."
  adminpw=$(slappasswd -h {SSHA} -s "${LDAP_SECRET}")
  adminpw=$(printf '%s\n' "$adminpw" | sed -e 's/[\/&]/\\&/g')
  sed -i s/ADMINPW/${adminpw}/g ${CONFIG_DIR}/configadminpw.ldif
  ldapmodify -Y EXTERNAL -H ldapi:/// -f ${CONFIG_DIR}/configadminpw.ldif -Q
}

configure_memberof_overlay(){
  echo "CНастроить оверлейe memberOf..."
  ldapmodify -Y EXTERNAL -H ldapi:/// -f ${CONFIG_DIR}/memberof.ldif -Q
}

force_starttls(){
  echo "Принудительный запуск StartTLS..."
  ldapmodify -Y EXTERNAL -H ldapi:/// -f ${CONFIG_DIR}/force-starttls.ldif -Q
}

load_initial_data() {
    echo "Загрузить данные..."
    local data=$(find ${DATA_DIR} -maxdepth 1 -name \*_\*.ldif -type f | sort)
    for ldif in ${data}; do
        echo "Обработка файла ${ldif}..."

        base_dn=${LDAP_BASEDN:-}
        if  [ ! -z "${base_dn}" ]; then
            echo "обновление базового dn dc=eden,dc=local -> ${base_dn}"
            sed -i "s/dc=eden,dc=local/${base_dn}/g" "${ldif}"
        fi

        domain=${LDAP_DOMAIN:-}
        if  [  "${domain}" != "eden.local" ]; then
            echo "обновление emails @eden.local -> @${domain}"
            sed -i "s/@eden.local/@${domain}/g" "${ldif}"
        fi

        ldapadd -x -H ldapi:/// \
          -D ${LDAP_BINDDN} \
          -w ${LDAP_SECRET} \
          -f ${ldif}
    done
}


## Инициализация


slapd -h "ldapi:///" -u openldap -g openldap

configure_msad_features
configure_tls
configure_logging
configure_memberof_overlay
configure_admin_config_pw
load_initial_data
if [ "$LDAP_FORCE_STARTTLS" == "true" ]; then
    force_starttls
fi

# Завершение работы демона openldap
kill -INT `cat /run/slapd/slapd.pid` && sleep 1
